import copy
from baseclasses import Piece, Error, InvalidMoveError
from general import General
from chariot import Chariot
from horse import Horse
from elephant import Elephant
from advisor import Advisor
from cannon import Cannon
from soldier import Soldier
import unittest

# red winning game
game = XiangqiGame()
print(game.make_move("c1", "e3"))
print(game.make_move("b8", "d8"))
print(game.make_move("g4", "g5"))
print(game.make_move("b10", "c8"))
print(game.make_move("c4", "c5"))
print(game.make_move("a10", "b10"))
print(game.make_move("a1", "a2"))
print(game.make_move("b10", "b3"))
print(game.make_move("h3", "b3"))
print(game.make_move("h10", "g8"))
print(game.make_move("a2", "d2"))
print(game.make_move("i10", "i9"))
print(game.make_move("i1", "i3"))
print(game.make_move("i9", "b9"))
print(game.make_move("b3", "b2"))
print(game.make_move("c7", "c6"))
print(game.make_move("c5", "c6"))
print(game.make_move("c8", "d6"))
print(game.make_move("d2", "d6"))
print(game.make_move("b9", "b2"))
print(game.make_move("g5", "g6"))
print(game.make_move("g7", "g6"))
print(game.make_move("d6", "g6"))
print(game.make_move("c10", "e8"))
print(game.make_move("g6", "d6"))
print(game.make_move("d10", "e9"))
print(game.make_move("i3", "h3"))
print(game.make_move("h8", "h1"))
print(game.make_move("h3", "h1"))
print(game.make_move("b2", "b1"))
print(game.make_move("h1", "h7"))
print(game.make_move("b1", "b4"))
print(game.make_move("e4", "e5"))
print(game.make_move("b4", "i4"))
print(game.make_move("c6", "c7"))
print(game.make_move("i4", "c4"))
print(game.make_move("d6", "d7"))
print(game.make_move("g8", "f6"))
print(game.make_move("h7", "e7"))
print(game.make_move("f6", "d7"))
print(game.make_move("c7", "d7"))
print(game.make_move("d8", "b8"))
print(game.make_move("e5", "e6"))
print(game.make_move("c4", "c6"))
print(game.make_move("g1", "i3"))
print(game.make_move("b8", "b4"))
print(game.make_move("f1", "e2"))
print(game.make_move("b4", "b1"))
print(game.make_move("e3", "c1"))
print(game.make_move("c6", "c1"))
print(game.make_move("e7", "f7"))
print(game.make_move("c1", "c2"))

# black winning game
game = XiangqiGame()
print(game.make_move("h3","e3"))
print(game.make_move("b10","c8"))
print(game.make_move("h1","g3"))
print(game.make_move("h8","f8"))
print(game.make_move("c4","c5"))
print(game.make_move("h10","g8"))
print(game.make_move("i1","h1"))
print(game.make_move("g7","g6"))
print(game.make_move("b3","d3"))
print(game.make_move("i10","i9"))
print(game.make_move("b1","a3"))
print(game.make_move("i9","d9"))
print(game.make_move("d1","e2"))
print(game.make_move("b8","a8"))
print(game.make_move("a1","b1"))
print(game.make_move("d9","d5"))
print(game.make_move("b1","b7"))
print(game.make_move("d5","c5"))
print(game.make_move("b7","b1"))
print(game.make_move("a8","a4"))
print(game.make_move("h1","h4"))
print(game.make_move("g8","f6"))
print(game.make_move("h4","h6"))
print(game.make_move("a4","g4"))
print(game.make_move("g1","i3"))
print(game.make_move("c10","e8"))
print(game.make_move("a3","b5"))
print(game.make_move("a10","b10"))
print(game.make_move("h6","h8"))
print(game.make_move("f10","e9"))
print(game.make_move("h8","h7"))
print(game.make_move("f6","d5"))
print(game.make_move("h7","h4"))
print(game.make_move("f8","g8"))
print(game.make_move("d3","d10"))
print(game.make_move("e10","d10"))
print(game.make_move("e3","d3"))
print(game.make_move("d5","f4"))
print(game.make_move("d3","d4"))
print(game.make_move("b10","b5"))
print(game.make_move("b1","b5"))
print(game.make_move("c5","c1"))
print(game.make_move("d4","d1"))
print(game.make_move("f4","g2"))
print(game.get_game_state())


# red winning
game = XiangqiGame()
print(game.make_move("h3","e3"))
print(game.make_move("h10","g8"))
print(game.make_move("h1","g3"))
print(game.make_move("i10","h10"))
print(game.make_move("i1","h1"))
print(game.make_move("b10","c8"))
print(game.make_move("c4","c5"))
print(game.make_move("g7","g6"))
print(game.make_move("h1","h8"))
print(game.make_move("h10","h8"))
print(game.make_move("b1","c3"))
print(game.make_move("g8","f6"))
print(game.make_move("a1","a2"))
print(game.make_move("h8","h6"))
print(game.make_move("b3","b6"))
print(game.make_move("a10","a9"))
print(game.make_move("a2","f2"))
print(game.make_move("a9","f9"))
print(game.make_move("c3","d5"))
print(game.make_move("h6","h5"))
print(game.make_move("b6","b5"))
print(game.make_move("c7","c6"))
print(game.make_move("d5","e7"))
print(game.make_move("c8","e7"))
print(game.make_move("b5","h5"))
print(game.make_move("g6","g5"))
print(game.make_move("g4","g5"))
print(game.make_move("b8","g8"))
print(game.make_move("g5","g6"))
print(game.make_move("g8","g3"))
print(game.make_move("e3","e7"))
print(game.make_move("f9","f7"))
print(game.make_move("h5","e5"))
print(game.get_game_state())
